### ISSUE TITLE
z3/z3++.h Not Found

### ISSUE THREAD

**Issue by racterub** [leetonidas/demovfuscator#9]
While compiling from source, it shows up the error message
![image](https://user-images.githubusercontent.com/20561837/39587723-c6f47294-4f2c-11e8-9aaa-16272afe93ad.png)

- z3 is compiled from source
- z3++.h is under /usr/include
- Z3 version 4.5.1 - 64 bit

**Comment by leetonidas** [comment]
Seems like the include path of z3 has been changed. Checked it on arch and debian to avoid breaking it for others... Fix in 41eb1df00fac2fb37fb83d00e33cff180ab5f006.
